spring.application.name=diabetes-assistant

server.port=8090
server.servlet.context-path=/diabetes

logging.level.com.diabetes.mapper=debug

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/diabetes_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=lyj342353602

mybatis-plus.mapper-locations=classpath:mapper/*.xml
mybatis-plus.type-aliases-package=com.diabetes.entity
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# JWT 配置
jwt.secret=DiabetesAssistant2026SecretKeyForJWTToken
jwt.expiration=86400000

# Dify 配置
dify.api-url=http://127.0.0.1/v1
dify.api-key=app-rmDSWHtuKqZpPfps7e2vL8n7
